# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fe016b7a3c07c5ed147b5be29b6cbc538252b6fac6b92c2294f23c2c67505837ed35d71f3d6aa68178653c2eac69def4881b656ed056c05bc0dafc804b7f1de7

test:
  secret_key_base: eae6c5eb95e3cdce9d4e37fc9892ff8d533e4c13c5a66a76fccefec3e2bd75ffdb7c20636d8cf2e880c2ace37b2bddf8ead0b8071f5c6ca2a6dab0823842cdc7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
